default: all

REGISTRY=nexus.teamdigitale.test
KYLO_SERVICES_PATH=../kylo0.9.1

.PHONY: activemq 
activemq:
	docker build -t tba-activemq -f docker/activemq/Dockerfile docker/activemq
	docker tag tba-activemq $REGISTRY/tba-activemq.5.15.1:1.1.0

.PHONY: mysql
mysql:
	mkdir -p docker/mysql/dist
	cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/setup/sql/mysql/kylo/* docker/mysql/dist
	docker build -t tba-mysql -f docker/mysql/Dockerfile docker/mysql
	docker tag tba-mysql $REGISTRY/tba-mysql.10.3:1.1.0
	rm -dr docker/mysql/dist

.PHONY: kylo-services
kylo-services:
		mkdir -p docker/kylo-services/dist/kylo-services && \
		if [ ! -f ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/kylo-services/lib/postgresql-42.1.4.jar ] ;then curl -o "${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/kylo-services/lib/postgresql-42.1.4.jar" http://central.maven.org/maven2/org/postgresql/postgresql/42.1.4/postgresql-42.1.4.jar  ;fi
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/kylo-services/lib docker/kylo-services/dist/kylo-services
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/kylo-services/plugin docker/kylo-services/dist/kylo-services
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/bin docker/kylo-services/dist
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/lib docker/kylo-services/dist
		docker build -t tba-kylo-services -f docker/kylo-services/Dockerfile docker/kylo-services
		docker tag tba-kylo-services ${REGISTRY}/tba-kylo-services.9.1:1.0.5-FIX
		rm -dr docker/kylo-services/dist

.PHONY: kylo-ui
kylo-ui:
		mkdir -p docker/kylo-ui/dist/kylo-ui
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/kylo-ui/lib docker/kylo-ui/dist/kylo-ui
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/kylo-ui/plugin docker/kylo-ui/dist/kylo-ui
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/bin docker/kylo-ui/dist
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/lib docker/kylo-ui/dist
		docker build -t tba-kylo-ui -f docker/kylo-ui/Dockerfile docker/kylo-ui
		docker tag tba-kylo-ui ${REGISTRY}/tba-kylo-ui.9.1:1.0.5-FIX
		rm -dr docker/kylo-ui/dist

.PHONY: nifi
nifi:
		mkdir -p docker/nifi/dist/daf
		cp -R ${KYLO_SERVICES_PATH}/install/install-tar/target/kylo/setup/nifi/* docker/nifi/dist
		cp -R ./nifi/extensions/processors/target/*.nar docker/nifi/dist/daf
		docker build -t tba-nifi -f docker/nifi/Dockerfile docker/nifi
		docker tag tba-nifi ${REGISTRY}/tba-nifi.1.6.0:1.2.6-CLUSTER
		rm -dr docker/nifi/dist

.PHONY: build-kylo
build-kylo:
	git clone https://github.com/Teradata/kylo.git ${KYLO_SERVICES_PATH} | true
	cd ${KYLO_SERVICES_PATH} && \
	git checkout release/0.9.1 && \
        git apply ../daf-kylo/kylo/patch/hive_patch.patch && \
    git apply kylo/patch/hive_patch.patch && \
	mvn clean install -DskipTests=true -U && \
	mkdir -p install/install-tar/target/kylo && \
	tar -C install/install-tar/target/kylo -xvf install/install-tar/target/kylo-*-dependencies.tar.gz

.PHONY: daf-kylo
daf-kylo:
	git clone https://github.com/italia/daf-kylo.git ../ ${KYLO_SERVICES_PATH} | true
	cd ../ ${KYLO_SERVICES_PATH} && \
    git checkout kylo_daf_0.9.1 && \
    git pull && \
    cd nifi/extensions && \
    mvn clean install -U
