apiVersion: v1
kind: Service
metadata:
  labels:
    app: tba-kylo-services
  name: tba-kylo-services
spec:
  type: "NodePort"
  ports:
  - name: "8420"
    port: 8420
    targetPort: 8420
    nodePort: 31420
  - name: "8450"
    port: 8450
    targetPort: 8450
    nodePort: 31429
  - name: "8451"
    port: 8451
    targetPort: 8451
    nodePort: 31493
  selector:
    app: tba-kylo-services
status:
  loadBalancer: {}