apiVersion: v1
kind: Service
metadata:
  labels:
    app: { tba-kylo-ui-app }
  name: { tba-kylo-ui-name }
spec:
  type: "NodePort"
  ports:
  - name: "8400"
    port: 8400
    targetPort: 8400
    nodePort: 30400
  selector:
    app: { tba-kylo-ui-name }
status:
  loadBalancer: {}